### ISSUE TITLE
Skipping upload on similarity check does not work anymore

### ISSUE THREAD

**Issue by LibertX** [reluce/szurubooru-toolkit#48]
Hello,

The skipping that occus when similarity checks occurs is now broken:

```
[WARNING] [11.12.2023, 03:09:42 UTC] [upload_media.check_similarity]: An error occured during the similarity check: Expecting value: line 1 column 1 (char 0). Skipping post...
139
138
137
136
135
134
133
132
Traceback (most recent call last):
131
  File "/usr/local/bin/upload-media", line 6, in <module>
130
    sys.exit(main())
129
             ^^^^^^
128
  File "/szurubooru-toolkit/src/szurubooru_toolkit/scripts/upload_media.py", line 327, in main
127
    success, saucenao_limit_reached = upload_post(
126
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
125
TypeError: cannot unpack non-iterable bool object
```

Thanks

**Comment by reluce** [comment]
This error message comes from szurubooru itself. Do other posts work or is it just the same post? Depending on how you run your szurubooru instance, you can try to restart it and try again.

**Comment by reluce** [comment]
I just pushed a fix to main, can you test it?
