### ISSUE TITLE
ModuleNotFoundError: No module named 'tweepy'

### ISSUE THREAD

**Issue by shibaobun** [reluce/szurubooru-toolkit#51]
Hello, I've been getting this issue from the docker container when I try to run the auto-tagger from the docker container :(

```
szuru-toolkit  | Traceback (most recent call last):
szuru-toolkit  |   File "/usr/local/bin/auto-tagger", line 3, in <module>
szuru-toolkit  |     from szurubooru_toolkit.scripts.auto_tagger import main
szuru-toolkit  |   File "/szurubooru-toolkit/src/szurubooru_toolkit/__init__.py", line 12, in <module>
szuru-toolkit  |     from .twitter import Twitter  # noqa F401
szuru-toolkit  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
szuru-toolkit  |   File "/szurubooru-toolkit/src/szurubooru_toolkit/twitter.py", line 4, in <module>
szuru-toolkit  |     import tweepy
szuru-toolkit  | ModuleNotFoundError: No module named 'tweepy'
```

**Comment by reluce** [comment]
I just pushed version 0.9.6 which should fix the issue. Version 1.0.0 will also be released later which also solves this issue.

**Comment by shibaobun** [comment]
Confirmed is fixed, thank you!!
