### ISSUE TITLE
"TypeError: cannot unpack non-iterable NoneType object" on import-from-url

### ISSUE THREAD

**Issue by Kalidibus** [reluce/szurubooru-toolkit#64]
`root@d7ed44db5a0a:/szurubooru-toolkit# szuru-toolkit import-from-url --cookies ./misc/cookies.txt --range ':100' 'https://x.com/kalidibus/likes/'`

`[INFO] Downloading posts from URLs ['https://x.com/kalidibus/likes/']...
[INFO] Downloaded 99 post(s). Start importing...
  4%|█▊                                          | 4/99 [00:05<01:44,  1.10s/it]`

`[WARNING] [upload_media.upload_file] An error occured during the upload for file "None": Parameter 'tags' must be a list of string values.
[ERROR] [szuru_toolkit.click_import_from_url] An error has been caught in function 'click_import_from_url', process 'MainProcess' (21), thread 'MainThread' (140255465323392):
Traceback (most recent call last):
  File "/szurubooru-toolkit/src/szurubooru_toolkit/scripts/szuru_toolkit.py", line 505, in click_import_from_url
    module.main(list(urls), input_file, add_tags, verbose)
  File "/szurubooru-toolkit/src/szurubooru_toolkit/scripts/import_from_url.py", line 193, in main
    saucenao_limit_reached = upload_media.main(
  File "/szurubooru-toolkit/src/szurubooru_toolkit/scripts/upload_media.py", line 435, in main
    _, saucenao_limit_reached = upload_post(file_to_upload, file_ext, metadata, saucenao_limit_reached=saucenao_limit_reached)
TypeError: cannot unpack non-iterable NoneType object
`

**Comment by Kalidibus** [comment]
Just to add some additional details, this is a brand new docker container using the current git repo as of yesterday.

Repeating the command fails on the same item to download each time it seems.

**Comment by reluce** [comment]
It seems that `post.tags` is `None`. Tags are being set from the gallery-dl json file:

https://github.com/reluce/szurubooru-toolkit/blob/e806a90eed7d462590eb5c08c9f5d3e118772013/src/szurubooru_toolkit/scripts/import_from_url.py#L216-L222

You can try to narrow it down by looking into each json file if there is something funky going on with the extracted tags. Or you could print `post.tags` in the exception statement:

https://github.com/reluce/szurubooru-toolkit/blob/e806a90eed7d462590eb5c08c9f5d3e118772013/src/szurubooru_toolkit/scripts/upload_media.py#L159-L161

For now, I'll set the tags to the default tags from `config.toml` in case they are `None`, so the upload should work. If `config.upload_media['tags']` is not set in your `config.toml`, it defaults to `tagme`.

I'll push a new release soon (`1.0.3`). In case it still doesn't work, you can re-open this issue.
